# Generated by Django 3.0.3 on 2020-06-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('League', 'Sports League'), ('Fitness', 'Online Fitness')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Catagories',
            },
        ),
        migrations.CreateModel(
            name='LeagueCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='LeagueOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='LeaguePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('Ind', 'Individual'), ('Team', 'Team')], max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Category')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Schedule')),
            ],
            options={
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='LeagueOrderPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.LeagueOrder')),
                ('league_packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.LeagueCart')),
            ],
        ),
        migrations.AddField(
            model_name='leagueorder',
            name='league_packages',
            field=models.ManyToManyField(through='commerce.LeagueOrderPackage', to='commerce.LeagueCart'),
        ),
        migrations.AddField(
            model_name='leagueorder',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='leaguecart',
            name='league_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.LeaguePackage'),
        ),
        migrations.AddField(
            model_name='leaguecart',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
    ]
