# Generated by Django 3.0.3 on 2020-06-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_stripe_customer'),
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name_plural': 'Game'},
        ),
        migrations.AlterUniqueTogether(
            name='teamplayer',
            unique_together={('team', 'player')},
        ),
    ]
