# Generated by Django 3.0.3 on 2020-06-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=50)),
                ('is_team_sport', models.BooleanField(default=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sport',
            },
        ),
    ]
