# Generated by Django 3.0.3 on 2020-06-24 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamplayer',
            old_name='date_joing',
            new_name='date_joined',
        ),
    ]
