# Generated by Django 3.0.3 on 2020-06-10 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=30)),
                ('team_limit', models.IntegerField(default=10)),
                ('schedule_description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_start_date', models.DateField()),
                ('season_end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.Sport')),
            ],
            options={
                'verbose_name_plural': 'Seasons',
            },
        ),
    ]
