# Generated by Django 3.0.3 on 2020-06-11 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200610_1210'),
        ('league', '0002_schedule_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateTimeField()),
                ('game_time', models.TimeField()),
                ('home_team_score', models.IntegerField(default=0)),
                ('away_team_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name_plural': 'Sports'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.Season'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='', max_length=50)),
                ('player', models.ManyToManyField(to='user.UserProfile')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='GameLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('post_code', models.CharField(max_length=10)),
                ('game', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Game')),
            ],
            options={
                'verbose_name_plural': 'GameLocations',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_team', to='league.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_team', to='league.Team'),
        ),
    ]
