# Generated by Django 3.0.3 on 2020-06-11 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20200611_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelocation',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='game_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.GameLocation'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.DateField(),
        ),
    ]
