# Generated by Django 3.0.3 on 2020-06-11 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_auto_20200611_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_team', to='league.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.GameLocation'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_team', to='league.Team'),
        ),
    ]
