# Generated by Django 3.0.3 on 2020-06-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_auto_20200611_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_name',
        ),
        migrations.AddField(
            model_name='schedule',
            name='compete_type',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced')], default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_day',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Fridayday'), ('6', 'Saturday'), ('2', 'Sunday')], default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(choices=[('1', 'Co-ed'), ('2', "Men's"), ('3', "Women's")], default=1, max_length=30),
        ),
    ]
