# Generated by Django 3.0.3 on 2020-06-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_auto_20200615_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamelocation',
            options={'verbose_name_plural': 'GameLocation'},
        ),
    ]
