# Generated by Django 3.0.3 on 2020-06-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_auto_20200615_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='compete_type',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Fridayday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(choices=[('Co-ed', 'Co-ed'), ("Men's", "Men's"), ("Women's", "Women's")], default=1, max_length=30),
        ),
    ]
