# Generated by Django 3.0.3 on 2020-06-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_stripe_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='stripe_customer',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
