# Generated by Django 3.0.3 on 2020-06-09 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_address_billingaddress_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='user',
            new_name='userprofile',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='user',
            new_name='userprofile',
        ),
    ]
