# Generated by Django 3.0.3 on 2020-06-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200610_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='userprofile',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='userprofile',
            new_name='user_profile',
        ),
    ]
