# Generated by Django 3.0.3 on 2020-06-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
